# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

services:
  app:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: archiveweb-app
    volumes:
      - ./homepage:/public
      - ./docker/nginx/conf/archiveweb.conf:/etc/nginx/conf.d/archiveweb.conf
    ports:
      - "8080:8080"

  job:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    command: tail -F anything
    container_name: archiveweb-job
    volumes:
      - ./homepage:/public
