# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: archiveweb-app
    volumes:
      - ./homepage:/public
      - ./docker/nginx/conf/archiveweb.conf:/etc/nginx/conf.d/archiveweb.conf
    ports:
      - "8080:8080"
      - "8443:8443"
