all:
  children:
    openshift_namespaces:
      hosts:
        archiveweb-openshift: {}
      vars:
        ansible_connection: local
        openshift_namespace: 'svc0041p-web-archiving'
        ansible_python_interpreter: '{{archivewebsible_suitcase_dir}}/bin/python3'
        routes_availability: public
        pv_name: svc0041p-web-archiving-pv
        pv_size: 20Gi
        tag: 2.4.1
    vms:
      hosts:
        itspress0001:
          ansible_host: itspress0001.xaas.epfl.ch
          ansible_user: root
          ansible_port: 22
          ansible_python_interpreter: "/usr/bin/python3"
