all:
  children:
    openshift_namespaces:
      hosts:
        blogs-wiki-prod: {}
      vars:
        ansible_connection: local
        openshift_namespace: 'blogs-wiki-prod'
        ansible_python_interpreter: '{{archivewebsible_suitcase_dir}}/bin/python3'
    vms:
      hosts:
        itspress0001:
          ansible_host: itspress0001.xaas.epfl.ch
          ansible_user: root
          ansible_port: 22
          ansible_python_interpreter: "/usr/bin/python3"
