- name: Archive Web Kubernetes objects
  hosts: openshift_namespaces
  gather_facts: yes
  roles:
    - role: roles/archiveweb-k8s

- name: Archive Web VM objects
  hosts: itspress0001
  gather_facts: no
  roles:
    - role: roles/archiveweb-vm
