- name: Archive Web Kubernetes objects
  hosts: openshift_namespaces
  gather_facts: true
  roles:
    - role: archiveweb-k8s

- name: Archive Web VM objects
  hosts: vms
  gather_facts: false
  roles:
    - role: archiveweb-vm
