app_name: 'archiveweb'
team: 'isas-fsd'

ghcr_registry: 'ghcr.io/epfl-si'
quay_registry: 'quay-its.epfl.ch/svc0041'

secrets: '{{ lookup("file", "/keybase/team/epfl_archiveweb/secrets.yml") | from_yaml }}'

dynamic_routes: '{{ lookup("file", "/keybase/team/epfl_archiveweb/hosts.yml") | from_yaml }}'
nginx_config: '{{ lookup("file", "/keybase/team/epfl_archiveweb/archiveweb.conf") }}'
