- name: Archive Web - ConfigMap
  openshift:
    state: latest
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: '{{ app_name }}-nginx-config'
      namespace: '{{ openshift_namespace }}'
      labels:
        app: '{{ app_name }}'
        team: '{{ team }}'
    data:
      archiveweb.conf: |
        {{ nginx_config }}
