- name: Archive Web - CronJob
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
      spec:
        schedule: '0 18 * * *'
        concurrencyPolicy: 'Replace'
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - name: '{{ app_name }}-job'
                    image: '{{ quay_registry }}/{{ app_name }}-job:{{ tag }}'
                    command: ["node", "/archiveweb/fill-archivedwebsites-json.js"]
                    volumeMounts:
                      - name: 'public'
                        mountPath: '/public'
                    resources:
                      limits:
                        cpu: 200m
                        memory: 200Mi
                      requests:
                        cpu: 100m
                        memory: 100Mi
                volumes:
                  - name: 'public'
                    persistentVolumeClaim:
                      claimName: '{{ app_name }}-pvc'
                restartPolicy: Never
