- name: Archive Web - CronJob
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
        labels:
          team: '{{ team }}'
          app.kubernetes.io/component: 'backend'
          app.kubernetes.io/managed-by: 'ansible'
          app.kubernetes.io/name: '{{ app_name }}-job'
          app.kubernetes.io/part-of: '{{ app_name }}'
          app.kubernetes.io/version: '{{ tag }}'
          app.openshift.io/runtime: 'nodejs'
        annotations:
          app.openshift.io/vcs-uri: 'https://github.com/epfl-si/homepage-archiveweb.epfl.ch/'
          app.openshift.io/vcs-ref: '{{ tag }}'
      spec:
        timeZone: 'Europe/Zurich'
        schedule: '0 7,10,13,16,19 * * *'
        concurrencyPolicy: 'Replace'
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: '{{ app_name }}-service-account'
                containers:
                  - name: '{{ app_name }}-job'
                    image: '{{ quay_registry }}/{{ app_name }}-job:{{ tag }}'
                    command: ["node", "/fill-archivedwebsites-json.js"]
                    volumeMounts:
                      - name: 'public'
                        mountPath: '/public'
                    resources:
                      limits:
                        memory: 64Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                volumes:
                  - name: 'public'
                    persistentVolumeClaim:
                      claimName: '{{ app_name }}-pvc'
                restartPolicy: Never
