- name: Images tasks
  ansible.builtin.include_tasks:
    file: 'images.yml'
    apply:
      tags: archiveweb.images
  tags: archiveweb.images

- name: Storage tasks
  ansible.builtin.include_tasks:
    file: 'storage.yml'
    apply:
      tags: archiveweb.storage
  tags: archiveweb.storage

- name: Secrets tasks
  ansible.builtin.include_tasks:
    file: 'secrets.yml'
    apply:
      tags: archiveweb.secrets
  tags: archiveweb.secrets

- name: Routes tasks
  ansible.builtin.include_tasks:
    file: 'routes.yml'
    apply:
      tags: archiveweb.routes
  tags: archiveweb.routes

- name: Nginx tasks
  ansible.builtin.include_tasks:
    file: 'nginx.yml'
    apply:
      tags: archiveweb.nginx
  tags:
    - archiveweb.nginx
    - archiveweb.nginx.restart

- name: CronJob tasks
  ansible.builtin.include_tasks:
    file: 'cronjob.yml'
    apply:
      tags: archiveweb.cronjob
  tags: archiveweb.cronjob
