- name: Images tasks
  ansible.builtin.include_tasks:
    file: 'images.yml'
    apply:
      tags: images
  tags: images

- name: Storage tasks
  ansible.builtin.include_tasks:
    file: 'storage.yml'
    apply:
      tags: storage
  tags: storage

- name: Secrets tasks
  ansible.builtin.include_tasks:
    file: 'secrets.yml'
    apply:
      tags: secrets
  tags: secrets

- name: Routes tasks
  ansible.builtin.include_tasks:
    file: 'routes.yml'
    apply:
      tags: routes
  tags: routes

- name: Nginx tasks
  ansible.builtin.include_tasks:
    file: 'nginx.yml'
    apply:
      tags: nginx
  tags:
    - nginx
    - nginx.restart

- name: CronJob tasks
  ansible.builtin.include_tasks:
    file: 'cronjob.yml'
    apply:
      tags: cronjob
  tags: cronjob
