- name: Image tasks
  include_tasks:
    file: 'image.yml'
    apply:
      tags: image
  tags: image

- name: Route tasks
  include_tasks:
    file: 'route.yml'
    apply:
      tags: route
  tags: route

- name: Web tasks
  include_tasks:
    file: 'web.yml'
    apply:
      tags: web
  tags:
    - web
    - web.restart

- name: CronJob tasks
  include_tasks:
    file: 'cronjob.yml'
    apply:
      tags: cronjob
  tags: cronjob
