- name: Archive Web - ServiceAccount
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: '{{ app_name }}-service-account'
        namespace: '{{ openshift_namespace }}'
      imagePullSecrets:
        - name: '{{ app_name }}-pull-secret'

- name: Archive Web - ConfigMap
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: '{{ app_name }}-nginx-config'
        namespace: '{{ openshift_namespace }}'
        labels:
          app: '{{ app_name }}'
          team: '{{ team }}'
      data:
        archiveweb.conf: |
          {{ nginx_config }}
  register: _archiveweb_configmap

- name: Archive Web - Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
        labels:
          app: '{{ app_name }}'
          team: '{{ team }}'
      spec:
        type: ClusterIP
        ports:
          - name: '80'
            port: 80
            targetPort: 8080
        selector:
          app: '{{ app_name }}'

- name: Archive Web - Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
        labels:
          app: '{{ app_name }}'
          team: '{{ team }}'
          version: '{{ tag }}'
      spec:
        replicas: 2
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        selector:
          matchLabels:
            app: '{{ app_name }}'
        template:
          metadata:
            labels:
              app: '{{ app_name }}'
              team: '{{ team }}'
              version: '{{ tag }}'
          spec:
            serviceAccountName: '{{ app_name }}-service-account'
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app: '{{ app_name }}'
                    topologyKey: kubernetes.io/hostname
            containers:
              - name: '{{ app_name }}'
                image: '{{ quay_registry }}/{{ app_name }}:{{ tag }}'
                volumeMounts:
                  - name: 'public'
                    mountPath: '/public'
                  - name: nginx-conf-volume
                    mountPath: /etc/nginx/conf.d
                resources:
                  limits:
                    cpu: 250m
                    memory: 256Mi
                  requests:
                    cpu: 100m
                    memory: 128Mi
                readinessProbe:
                  httpGet:
                    scheme: HTTP
                    path: /index.html
                    port: 8080
                  initialDelaySeconds: 2
                  timeoutSeconds: 2
            volumes:
              - name: 'public'
                persistentVolumeClaim:
                  claimName: '{{ app_name }}-pvc'
              - name: nginx-conf-volume
                configMap:
                  name: '{{ app_name }}-nginx-config'

- name: Archive Web - Restart
  when: >-
    ('archiveweb.nginx.restart' in ansible_run_tags)
    or
    ( (_archiveweb_configmap | default({})) is changed )
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    definition:
      metadata:
        name: '{{ app_name }}'
        namespace: '{{ openshift_namespace }}'
      spec:
        template:
          metadata:
            annotations:
              last-restart: '{{ ansible_date_time.iso8601 }}'
  tags: archiveweb.nginx.restart
