# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Lint
        run: |
          make lint

  build-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Build app image

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build app image
        run: |
          docker build . \
            --no-cache \
            --file docker/nginx/Dockerfile \
            --tag archiveweb

      - name: Log in to the Container registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push app image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_ID="ghcr.io/epfl-si/archiveweb"

          docker tag archiveweb $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

          docker tag archiveweb $IMAGE_ID:$GITHUB_REF_NAME
          docker push $IMAGE_ID:$GITHUB_REF_NAME

  build-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Build job image

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build job image
        run: |
          docker build . \
            --no-cache \
            --file docker/nodejs/Dockerfile \
            --tag archiveweb-job

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push job image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_ID="ghcr.io/epfl-si/archiveweb-job"

          docker tag archiveweb-job $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

          docker tag archiveweb-job $IMAGE_ID:$GITHUB_REF_NAME
          docker push $IMAGE_ID:$GITHUB_REF_NAME
