# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint
        run: |
          make lint
