# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint
        run: |
          make lint

  build-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Build

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . \
            --no-cache \
            --file docker/nginx/Dockerfile \
            --tag archiveweb
