# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, 2022.

name: Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint
        run: |
          make lint

  build-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Build and scan app image

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . \
            --no-cache \
            --file docker/nginx/Dockerfile \
            --tag archiveweb

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.5.1
        with:
          image-ref: 'archiveweb'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
